<a href="https://colab.research.google.com/github/Siddharth5723/Daily_learning/blob/main/Decision_tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
data = {
    'Company': [
        'Google', 'Amazon', 'Walmart', 'Tesla', 'Meta', 'Starbucks', 'Microsoft', 'Netflix',
        'Ford', 'JPMorgan', 'Goldman Sachs', 'Mayo Clinic', 'NVIDIA', 'Intel', 'FedEx',
        'Apple', 'Pfizer', 'Boeing', 'Target', 'Adobe', 'Oracle', 'IBM', 'Uber', 'Airbnb',
        'Spotify', 'Salesforce', 'SpaceX', 'Costco', 'Delta', 'PepsiCo'
    ],
    'Job': [
        'Software Engineer', 'Data Scientist', 'Logistics Manager', 'Mechanical Engineer',
        'UX Designer', 'Store Manager', 'Product Manager', 'Content Strategist',
        'Assembly Lead', 'Financial Analyst', 'Investment Banker', 'Registered Nurse',
        'Hardware Engineer', 'Systems Architect', 'Operations Analyst', 'iOS Developer',
        'Research Scientist', 'Aerospace Engineer', 'Marketing Specialist', 'Sales Executive',
        'Database Admin', 'Cloud Consultant', 'Backend Developer', 'Data Analyst',
        'Backend Engineer', 'CRM Consultant', 'Propulsion Engineer', 'Warehouse Manager',
        'Commercial Pilot', 'Supply Chain Planner'
    ],
    'Degree': [
        'Masters', 'PhD', 'Bachelors', 'Bachelors', 'Bachelors', 'Associates', 'MBA', 'Bachelors',
        'High School', 'Bachelors', 'MBA', 'Bachelors', 'Masters', 'PhD', 'Bachelors',
        'Bachelors', 'PhD', 'Masters', 'Bachelors', 'Bachelors', 'Bachelors', 'Masters',
        'Bachelors', 'Masters', 'Bachelors', 'Bachelors', 'PhD', 'Associates', 'Bachelors', 'Bachelors'
    ],
    'Salary_more_than_100k': [
        'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No',
        'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No',
        'Yes', 'No', 'Yes', 'No', 'Yes', 'No'
    ]
}

df = pd.DataFrame(data)
df.head()

   Company                  Job     Degree Salary_more_than_100k
0   Google    Software Engineer    Masters                   Yes
1   Amazon       Data Scientist        PhD                   Yes
2  Walmart    Logistics Manager  Bachelors                    No
3    Tesla  Mechanical Engineer  Bachelors                   Yes
4     Meta          UX Designer  Bachelors                   Yes

In [2]:
df['Salary_more_than_100k'] = df['Salary_more_than_100k'].map({'Yes': 1, 'No': 0})

In [3]:
df.head()

   Company                  Job     Degree  Salary_more_than_100k
0   Google    Software Engineer    Masters                      1
1   Amazon       Data Scientist        PhD                      1
2  Walmart    Logistics Manager  Bachelors                      0
3    Tesla  Mechanical Engineer  Bachelors                      1
4     Meta          UX Designer  Bachelors                      1

In [4]:
inputs = df.drop('Salary_more_than_100k', axis='columns')
target = df['Salary_more_than_100k']

In [5]:
inputs

          Company                   Job       Degree
0          Google     Software Engineer      Masters
1          Amazon        Data Scientist          PhD
2         Walmart     Logistics Manager    Bachelors
3           Tesla   Mechanical Engineer    Bachelors
4            Meta           UX Designer    Bachelors
5       Starbucks         Store Manager   Associates
6       Microsoft       Product Manager          MBA
7         Netflix    Content Strategist    Bachelors
8            Ford         Assembly Lead  High School
9        JPMorgan     Financial Analyst    Bachelors
10  Goldman Sachs     Investment Banker          MBA
11    Mayo Clinic      Registered Nurse    Bachelors
12         NVIDIA     Hardware Engineer      Masters
13          Intel     Systems Architect          PhD
14          FedEx    Operations Analyst    Bachelors
15          Apple         iOS Developer    Bachelors
16         Pfizer    Research Scientist          PhD
17         Boeing    Aerospace Engineer      Masters
18         Target  Marketing Specialist    Bachelors
19          Adobe       Sales Executive    Bachelors
20         Oracle        Database Admin    Bachelors
21            IBM      Cloud Consultant      Masters
22           Uber     Backend Developer    Bachelors
23         Airbnb          Data Analyst      Masters
24        Spotify      Backend Engineer    Bachelors
25     Salesforce        CRM Consultant    Bachelors
26         SpaceX   Propulsion Engineer          PhD
27         Costco     Warehouse Manager   Associates
28          Delta      Commercial Pilot    Bachelors
29        PepsiCo  Supply Chain Planner    Bachelors

In [6]:
target

0     1
1     1
2     0
3     1
4     1
5     0
6     1
7     1
8     0
9     0
10    1
11    0
12    1
13    1
14    0
15    1
16    1
17    1
18    0
19    1
20    0
21    1
22    1
23    0
24    1
25    0
26    1
27    0
28    1
29    0
Name: Salary_more_than_100k, dtype: int64

In [7]:
from sklearn.preprocessing import LabelEncoder

In [15]:
le_Company = LabelEncoder()
le_Job = LabelEncoder()
le_Degree = LabelEncoder()

In [16]:
inputs['Company_n'] = le_Company.fit_transform(inputs['Company'])
inputs['Job_n'] = le_Job.fit_transform(inputs['Job'])
inputs['Degree_n'] = le_Degree.fit_transform(inputs['Degree'])

In [18]:
inputs.head()

   Company                  Job     Degree  Company_n  Job_n  Degree_n
0   Google    Software Engineer    Masters         10     23         4
1   Amazon       Data Scientist        PhD          2      9         5
2  Walmart    Logistics Manager  Bachelors         29     14         1
3    Tesla  Mechanical Engineer  Bachelors         27     16         1
4     Meta          UX Designer  Bachelors         15     27         1

In [19]:
inputs_n = inputs.drop(['Company' , 'Job' , "Degree"] , axis = 'columns')

In [21]:
inputs_n.head()

   Company_n  Job_n  Degree_n
0         10     23         4
1          2      9         5
2         29     14         1
3         27     16         1
4         15     27         1

In [22]:
from sklearn import tree

In [23]:
model = tree.DecisionTreeClassifier()

In [24]:
model.fit(inputs_n,target)

DecisionTreeClassifier()

In [26]:
model.score(inputs_n,target) # over fitted model because there was no train_test_split used

1.0

In [27]:
model.predict([[2,2,1]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])