<a href="https://colab.research.google.com/github/Siddharth5723/Daily_learning/blob/main/Naive_bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

# Creating the dataset as a list of dictionaries
titanic_data = [
    {"PassengerId": 1, "Name": "Braund, Mr. Owen Harris", "Pclass": 3, "Sex": "male", "Age": 22.0, "SibSp": 1, "Parch": 0, "Ticket": "A/5 21171", "Fare": 7.25, "Cabin": None, "Embarked": "S", "Survived": 0},
    {"PassengerId": 2, "Name": "Cumings, Mrs. John Bradley (Florence Briggs Thayer)", "Pclass": 1, "Sex": "female", "Age": 38.0, "SibSp": 1, "Parch": 0, "Ticket": "PC 17599", "Fare": 71.2833, "Cabin": "C85", "Embarked": "C", "Survived": 1},
    {"PassengerId": 3, "Name": "Heikkinen, Miss. Laina", "Pclass": 3, "Sex": "female", "Age": 26.0, "SibSp": 0, "Parch": 0, "Ticket": "STON/O2. 3101282", "Fare": 7.925, "Cabin": None, "Embarked": "S", "Survived": 1},
    {"PassengerId": 4, "Name": "Futrelle, Mrs. Jacques Heath (Lily May Peel)", "Pclass": 1, "Sex": "female", "Age": 35.0, "SibSp": 1, "Parch": 0, "Ticket": "113803", "Fare": 53.1, "Cabin": "C123", "Embarked": "S", "Survived": 1},
    {"PassengerId": 5, "Name": "Allen, Mr. William Henry", "Pclass": 3, "Sex": "male", "Age": 35.0, "SibSp": 0, "Parch": 0, "Ticket": "373450", "Fare": 8.05, "Cabin": None, "Embarked": "S", "Survived": 0},
    {"PassengerId": 6, "Name": "Moran, Mr. James", "Pclass": 3, "Sex": "male", "Age": np.nan, "SibSp": 0, "Parch": 0, "Ticket": "330877", "Fare": 8.4583, "Cabin": None, "Embarked": "Q", "Survived": 0},
    {"PassengerId": 7, "Name": "McCarthy, Mr. Timothy J", "Pclass": 1, "Sex": "male", "Age": 54.0, "SibSp": 0, "Parch": 0, "Ticket": "17463", "Fare": 51.8625, "Cabin": "E46", "Embarked": "S", "Survived": 0},
    {"PassengerId": 8, "Name": "Palsson, Master. Gosta Leonard", "Pclass": 3, "Sex": "male", "Age": 2.0, "SibSp": 3, "Parch": 1, "Ticket": "349909", "Fare": 21.075, "Cabin": None, "Embarked": "S", "Survived": 0},
    {"PassengerId": 9, "Name": "Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)", "Pclass": 3, "Sex": "female", "Age": 27.0, "SibSp": 0, "Parch": 2, "Ticket": "347742", "Fare": 11.1333, "Cabin": None, "Embarked": "S", "Survived": 1},
    {"PassengerId": 10, "Name": "Nasser, Mrs. Nicholas (Adele Achem)", "Pclass": 2, "Sex": "female", "Age": 14.0, "SibSp": 1, "Parch": 0, "Ticket": "237736", "Fare": 30.0708, "Cabin": None, "Embarked": "C", "Survived": 1},
    {"PassengerId": 11, "Name": "Sandstrom, Miss. Marguerite Rut", "Pclass": 3, "Sex": "female", "Age": 4.0, "SibSp": 1, "Parch": 1, "Ticket": "PP 9549", "Fare": 16.7, "Cabin": "G6", "Embarked": "S", "Survived": 1},
    {"PassengerId": 12, "Name": "Bonnell, Miss. Elizabeth", "Pclass": 1, "Sex": "female", "Age": 58.0, "SibSp": 0, "Parch": 0, "Ticket": "113783", "Fare": 26.55, "Cabin": "C103", "Embarked": "S", "Survived": 1},
    {"PassengerId": 13, "Name": "Saundercock, Mr. William Henry", "Pclass": 3, "Sex": "male", "Age": 20.0, "SibSp": 0, "Parch": 0, "Ticket": "A/5. 2151", "Fare": 8.05, "Cabin": None, "Embarked": "S", "Survived": 0},
    {"PassengerId": 14, "Name": "Andersson, Mr. Anders Johan", "Pclass": 3, "Sex": "male", "Age": 39.0, "SibSp": 1, "Parch": 5, "Ticket": "347082", "Fare": 31.275, "Cabin": None, "Embarked": "S", "Survived": 0},
    {"PassengerId": 15, "Name": "Vestrom, Miss. Hulda Amanda Adolfina", "Pclass": 3, "Sex": "female", "Age": 14.0, "SibSp": 0, "Parch": 0, "Ticket": "350406", "Fare": 7.8542, "Cabin": None, "Embarked": "S", "Survived": 0},
    {"PassengerId": 16, "Name": "Hewlett, Mrs. (Mary D Kingcome)", "Pclass": 2, "Sex": "female", "Age": 55.0, "SibSp": 0, "Parch": 0, "Ticket": "248706", "Fare": 16.0, "Cabin": None, "Embarked": "S", "Survived": 1},
    {"PassengerId": 17, "Name": "Rice, Master. Eugene", "Pclass": 3, "Sex": "male", "Age": 2.0, "SibSp": 4, "Parch": 1, "Ticket": "382652", "Fare": 29.125, "Cabin": None, "Embarked": "Q", "Survived": 0},
    {"PassengerId": 18, "Name": "Williams, Mr. Charles Eugene", "Pclass": 2, "Sex": "male", "Age": np.nan, "SibSp": 0, "Parch": 0, "Ticket": "244373", "Fare": 13.0, "Cabin": None, "Embarked": "S", "Survived": 1},
    {"PassengerId": 19, "Name": "Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)", "Pclass": 3, "Sex": "female", "Age": 31.0, "SibSp": 1, "Parch": 0, "Ticket": "345763", "Fare": 18.0, "Cabin": None, "Embarked": "S", "Survived": 0},
    {"PassengerId": 20, "Name": "Masselmani, Mrs. Fatima", "Pclass": 3, "Sex": "female", "Age": np.nan, "SibSp": 0, "Parch": 0, "Ticket": "2649", "Fare": 7.225, "Cabin": None, "Embarked": "C", "Survived": 1},
    {"PassengerId": 21, "Name": "Fynney, Mr. Joseph J", "Pclass": 2, "Sex": "male", "Age": 35.0, "SibSp": 0, "Parch": 0, "Ticket": "239865", "Fare": 26.0, "Cabin": None, "Embarked": "S", "Survived": 0},
    {"PassengerId": 22, "Name": "Beesley, Mr. Lawrence", "Pclass": 2, "Sex": "male", "Age": 34.0, "SibSp": 0, "Parch": 0, "Ticket": "248698", "Fare": 13.0, "Cabin": "D56", "Embarked": "S", "Survived": 1},
    {"PassengerId": 23, "Name": "McGowan, Miss. Anna \"Annie\"", "Pclass": 3, "Sex": "female", "Age": 15.0, "SibSp": 0, "Parch": 0, "Ticket": "330923", "Fare": 8.0292, "Cabin": None, "Embarked": "Q", "Survived": 1},
    {"PassengerId": 24, "Name": "Sloper, Mr. William Thompson", "Pclass": 1, "Sex": "male", "Age": 28.0, "SibSp": 0, "Parch": 0, "Ticket": "113788", "Fare": 35.5, "Cabin": "A6", "Embarked": "S", "Survived": 1},
    {"PassengerId": 25, "Name": "Palsson, Miss. Torborg Danira", "Pclass": 3, "Sex": "female", "Age": 8.0, "SibSp": 3, "Parch": 1, "Ticket": "349909", "Fare": 21.075, "Cabin": None, "Embarked": "S", "Survived": 0},
    {"PassengerId": 26, "Name": "Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)", "Pclass": 3, "Sex": "female", "Age": 38.0, "SibSp": 1, "Parch": 5, "Ticket": "347077", "Fare": 31.3875, "Cabin": None, "Embarked": "S", "Survived": 1},
    {"PassengerId": 27, "Name": "Emir, Mr. Farred Chehab", "Pclass": 3, "Sex": "male", "Age": np.nan, "SibSp": 0, "Parch": 0, "Ticket": "2631", "Fare": 7.225, "Cabin": None, "Embarked": "C", "Survived": 0},
    {"PassengerId": 28, "Name": "Fortune, Mr. Charles Alexander", "Pclass": 1, "Sex": "male", "Age": 19.0, "SibSp": 3, "Parch": 2, "Ticket": "19950", "Fare": 263.0, "Cabin": "C23 C25 C27", "Embarked": "S", "Survived": 0},
    {"PassengerId": 29, "Name": "O'Dwyer, Miss. Ellen \"Nellie\"", "Pclass": 3, "Sex": "female", "Age": np.nan, "SibSp": 0, "Parch": 0, "Ticket": "330959", "Fare": 7.8792, "Cabin": None, "Embarked": "Q", "Survived": 1},
    {"PassengerId": 30, "Name": "Todoroff, Mr. Lalio", "Pclass": 3, "Sex": "male", "Age": np.nan, "SibSp": 0, "Parch": 0, "Ticket": "349216", "Fare": 7.8958, "Cabin": None, "Embarked": "S", "Survived": 0},
    {"PassengerId": 31, "Name": "Uruchurtu, Don. Manuel E", "Pclass": 1, "Sex": "male", "Age": 40.0, "SibSp": 0, "Parch": 0, "Ticket": "PC 17601", "Fare": 27.7208, "Cabin": None, "Embarked": "C", "Survived": 0},
    {"PassengerId": 32, "Name": "Spencer, Mrs. William Augustus (Marie Eugenie)", "Pclass": 1, "Sex": "female", "Age": np.nan, "SibSp": 1, "Parch": 0, "Ticket": "PC 17569", "Fare": 146.5208, "Cabin": "B78", "Embarked": "C", "Survived": 1},
    {"PassengerId": 33, "Name": "Glynn, Miss. Mary Agatha", "Pclass": 3, "Sex": "female", "Age": np.nan, "SibSp": 0, "Parch": 0, "Ticket": "335677", "Fare": 7.75, "Cabin": None, "Embarked": "Q", "Survived": 1},
    {"PassengerId": 34, "Name": "Wheadon, Mr. Edward H", "Pclass": 2, "Sex": "male", "Age": 66.0, "SibSp": 0, "Parch": 0, "Ticket": "C.A. 24579", "Fare": 10.5, "Cabin": None, "Embarked": "S", "Survived": 0},
    {"PassengerId": 35, "Name": "Meyer, Mr. Edgar Joseph", "Pclass": 1, "Sex": "male", "Age": 28.0, "SibSp": 1, "Parch": 0, "Ticket": "PC 17604", "Fare": 82.1708, "Cabin": None, "Embarked": "C", "Survived": 0},
    {"PassengerId": 36, "Name": "Holverson, Mr. Alexander Oskar", "Pclass": 1, "Sex": "male", "Age": 42.0, "SibSp": 1, "Parch": 0, "Ticket": "113789", "Fare": 52.0, "Cabin": None, "Embarked": "S", "Survived": 0},
    {"PassengerId": 37, "Name": "Mamee, Mr. Hanna", "Pclass": 3, "Sex": "male", "Age": np.nan, "SibSp": 0, "Parch": 0, "Ticket": "2677", "Fare": 7.2292, "Cabin": None, "Embarked": "C", "Survived": 1},
    {"PassengerId": 38, "Name": "Cann, Mr. Ernest Charles", "Pclass": 3, "Sex": "male", "Age": 21.0, "SibSp": 0, "Parch": 0, "Ticket": "A./5. 2152", "Fare": 8.05, "Cabin": None, "Embarked": "S", "Survived": 0},
    {"PassengerId": 39, "Name": "Vander Planke, Miss. Augusta Maria", "Pclass": 3, "Sex": "female", "Age": 18.0, "SibSp": 2, "Parch": 0, "Ticket": "345764", "Fare": 18.0, "Cabin": None, "Embarked": "S", "Survived": 0},
    {"PassengerId": 40, "Name": "Nicola-Yarred, Miss. Jamila", "Pclass": 3, "Sex": "female", "Age": 14.0, "SibSp": 1, "Parch": 0, "Ticket": "2651", "Fare": 11.2417, "Cabin": None, "Embarked": "C", "Survived": 1}
]

# Initializing the DataFrame
df = pd.DataFrame(titanic_data)

In [ ]:
df.head()

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,None,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,None,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,None,S,0

In [ ]:
df.isnull().sum()

PassengerId     0
Name            0
Pclass          0
Sex             0
Age             9
SibSp           0
Parch           0
Ticket          0
Fare            0
Cabin          31
Embarked        0
Survived        0
dtype: int64

In [ ]:
df = df.drop(columns=['Cabin'])

In [ ]:
df.isnull().sum()

PassengerId    0
Name           0
Pclass         0
Sex            0
Age            9
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
Survived       0
dtype: int64

In [ ]:
df.drop(['PassengerId','Name' , 'SibSp' , 'Parch', 'Ticket' , 'Embarked'],axis='columns',inplace=True)
df.head()

   Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [ ]:
target = df.Survived
inputs = df.drop('Survived', axis='columns')

In [ ]:
dummies = pd.get_dummies(inputs.Sex, dtype=int)
dummies.head(3)

   female  male
0       0     1
1       1     0
2       1     0

In [ ]:
inputs = pd.concat([inputs,dummies], axis='columns')
inputs.head(3)

   Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0

In [ ]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [ ]:
inputs.Age[::10]

0     22.0
10     4.0
20    35.0
30    40.0
Name: Age, dtype: float64

In [ ]:
inputs = inputs.drop(columns = ['Sex'])

In [ ]:
inputs.head()

   Pclass   Age     Fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0
3       1  35.0  53.1000       1     0
4       3  35.0   8.0500       0     1

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train , y_test = train_test_split(inputs, target, test_size=0.2)

In [ ]:
len(X_train)

32

In [ ]:
len(X_test)

8

In [ ]:
X_train

    Pclass   Age      Fare  female  male
12       3  20.0    8.0500       0     1
22       3  15.0    8.0292       1     0
4        3  35.0    8.0500       0     1
37       3  21.0    8.0500       0     1
11       1  58.0   26.5500       1     0
33       2  66.0   10.5000       0     1
31       1   NaN  146.5208       1     0
38       3  18.0   18.0000       1     0
14       3  14.0    7.8542       1     0
15       2  55.0   16.0000       1     0
10       3   4.0   16.7000       1     0
1        1  38.0   71.2833       1     0
24       3   8.0   21.0750       1     0
36       3   NaN    7.2292       0     1
26       3   NaN    7.2250       0     1
28       3   NaN    7.8792       1     0
5        3   NaN    8.4583       0     1
0        3  22.0    7.2500       0     1
3        1  35.0   53.1000       1     0
9        2  14.0   30.0708       1     0
23       1  28.0   35.5000       0     1
30       1  40.0   27.7208       0     1
35       1  42.0   52.0000       0     1
21       2  34.0   13.0000       0     1
29       3   NaN    7.8958       0     1
25       3  38.0   31.3875       1     0
2        3  26.0    7.9250       1     0
7        3   2.0   21.0750       0     1
32       3   NaN    7.7500       1     0
16       3   2.0   29.1250       0     1
34       1  28.0   82.1708       0     1
18       3  31.0   18.0000       1     0

In [ ]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [ ]:
X_train_imputed = X_train.copy()
X_test_imputed = X_test.copy()

X_train_imputed['Age'] = X_train_imputed['Age'].fillna(X_train_imputed['Age'].mean())
X_test_imputed['Age'] = X_test_imputed['Age'].fillna(X_test_imputed['Age'].mean())

model.fit(X_train_imputed, y_train)

GaussianNB()

In [ ]:
model.score(X_test_imputed , y_test)

0.75

In [ ]:
y_test[:10]

20    0
6     0
17    1
8     1
27    0
13    0
19    1
39    1
Name: Survived, dtype: int64

In [ ]:
model.predict(X_test_imputed[:10])

array([0, 0, 0, 1, 1, 0, 1, 1])

In [ ]:
model.predict_proba(X_test_imputed[:10])

array([[9.79854304e-01, 2.01456958e-02],
       [8.29383174e-01, 1.70616826e-01],
       [9.83005864e-01, 1.69941359e-02],
       [1.26788132e-01, 8.73211868e-01],
       [1.36122460e-24, 1.00000000e+00],
       [9.86737364e-01, 1.32626362e-02],
       [1.11672714e-01, 8.88327286e-01],
       [1.80977924e-01, 8.19022076e-01]])

### Naive Bayes Classifiers

Naive Bayes classifiers are a family of simple probabilistic classifiers based on applying Bayes' theorem with strong (naive) independence assumptions between the features. They are known for their simplicity, efficiency, and effectiveness, especially in text classification and other high-dimensional datasets.

There are several types of Naive Bayes classifiers, each suited for different types of data distribution:

1.  **Gaussian Naive Bayes**: Used when features are continuous and assumed to be distributed according to a Gaussian (normal) distribution.
2.  **Multinomial Naive Bayes**: Suitable for discrete features (e.g., word counts for text classification). It is commonly used for document classification problems.
3.  **Bernoulli Naive Bayes**: Designed for binary or boolean features. It assumes that each feature is a Bernoulli distributed variable (i.e., it can take on only two values, typically 0 or 1).

#### Gaussian Naive Bayes (Recap)

As already implemented, Gaussian Naive Bayes assumes that continuous features associated with each class are distributed according to a Gaussian distribution. This is often a good default choice for continuous data.

#### Evaluating the Gaussian Naive Bayes Model

Let's add more evaluation metrics to assess the performance of our Gaussian Naive Bayes model, such as a Confusion Matrix and a Classification Report.

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

y_pred_gnb = model.predict(X_test_imputed)

print("--- Gaussian Naive Bayes Evaluation ---")
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_gnb))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_gnb))

--- Gaussian Naive Bayes Evaluation ---
Confusion Matrix:
[[3 1]
 [1 3]]

Classification Report:
              precision    recall  f1-score   support

           0       0.75      0.75      0.75         4
           1       0.75      0.75      0.75         4

    accuracy                           0.75         8
   macro avg       0.75      0.75      0.75         8
weighted avg       0.75      0.75      0.75         8

#### Multinomial Naive Bayes

Multinomial Naive Bayes is suitable for classification with discrete features (e.g., word counts in text classification). The feature values should be counts or frequencies. While our current features (`Pclass`, `Age`, `Fare`) are not strictly counts, `Pclass` could be treated as discrete, and `Age`/`Fare` could be binned or scaled for MultinomialNB if required. For demonstration, we'll apply it directly here, but ideally, preprocessing (like scaling or binning for continuous features) might be needed for optimal performance.

For `MultinomialNB`, feature values must be non-negative. We'll ensure this by replacing any negative values with 0 if they exist (though unlikely in this dataset).

In [ ]:
from sklearn.naive_bayes import MultinomialNB

# Ensure non-negative features for MultinomialNB
# Age and Fare can sometimes have outliers or be problematic if not handled,
# but for simplicity, we'll assume they are fine after imputation for now.
# If there were negative Fares (which shouldn't happen), we'd need to address it.
# Let's create a copy of inputs for MultinomialNB to be safe with potential future modifications
inputs_mnb = inputs.copy()

# A simple check to ensure no negative values before fitting MultinomialNB
# While unlikely for Age/Fare, it's good practice.
# We will fill NaN in Age with the mean to make it compatible.
inputs_mnb['Age'] = inputs_mnb['Age'].fillna(inputs_mnb['Age'].mean())

# Convert floats to integers if appropriate, or ensure non-negativity for MNB
# Pclass, female, male are already good.
# Age and Fare need to be non-negative. Also, MNB often expects count-like data.
# For demonstration, we'll just ensure non-negativity.
inputs_mnb[inputs_mnb < 0] = 0


X_train_mnb, X_test_mnb, y_train_mnb, y_test_mnb = train_test_split(inputs_mnb, target, test_size=0.2, random_state=42)

model_mnb = MultinomialNB()
model_mnb.fit(X_train_mnb, y_train_mnb)

print("--- Multinomial Naive Bayes Evaluation ---")
print(f"Multinomial Naive Bayes Accuracy: {model_mnb.score(X_test_mnb, y_test_mnb)}")

y_pred_mnb = model_mnb.predict(X_test_mnb)
print("Confusion Matrix:")
print(confusion_matrix(y_test_mnb, y_pred_mnb))
print("\nClassification Report:")
print(classification_report(y_test_mnb, y_pred_mnb))

--- Multinomial Naive Bayes Evaluation ---
Multinomial Naive Bayes Accuracy: 0.5
Confusion Matrix:
[[4 2]
 [2 0]]

Classification Report:
              precision    recall  f1-score   support

           0       0.67      0.67      0.67         6
           1       0.00      0.00      0.00         2

    accuracy                           0.50         8
   macro avg       0.33      0.33      0.33         8
weighted avg       0.50      0.50      0.50         8

#### Bernoulli Naive Bayes

Bernoulli Naive Bayes is designed for binary/boolean features. It explicitly models the presence or absence of a particular feature. It's often used when features represent whether a term is present or not in a document (as opposed to its count).

For our dataset, we can binarize `Age` and `Fare` (e.g., above/below mean/median) or use the existing binary `female`/`male` and discrete `Pclass` features directly. For `BernoulliNB`, features are typically 0 or 1. Let's create a binarized version of `Age` and `Fare` for this model, and use `Pclass` as is (it will be treated as binary if it only had 0s and 1s, otherwise it's just a numerical feature where its presence/absence is modeled).

Here, we'll simplify by thresholding `Age` and `Fare` at their means to create binary features.

In [ ]:
from sklearn.naive_bayes import BernoulliNB

# Create a binarized version of the inputs for BernoulliNB
inputs_bnb = inputs.copy()

# Fill NaN in Age with the mean for binarization
inputs_bnb['Age'] = inputs_bnb['Age'].fillna(inputs_bnb['Age'].mean())

# Binarize Age and Fare
inputs_bnb['Age_Binarized'] = (inputs_bnb['Age'] > inputs_bnb['Age'].mean()).astype(int)
inputs_bnb['Fare_Binarized'] = (inputs_bnb['Fare'] > inputs_bnb['Fare'].mean()).astype(int)

# Drop original Age and Fare columns, keep Pclass, female, male, and new binarized features
inputs_bnb = inputs_bnb.drop(columns=['Age', 'Fare'])

X_train_bnb, X_test_bnb, y_train_bnb, y_test_bnb = train_test_split(inputs_bnb, target, test_size=0.2, random_state=42)

model_bnb = BernoulliNB()
model_bnb.fit(X_train_bnb, y_train_bnb)

print("--- Bernoulli Naive Bayes Evaluation ---")
print(f"Bernoulli Naive Bayes Accuracy: {model_bnb.score(X_test_bnb, y_test_bnb)}")

y_pred_bnb = model_bnb.predict(X_test_bnb)
print("Confusion Matrix:")
print(confusion_matrix(y_test_bnb, y_pred_bnb))
print("\nClassification Report:")
print(classification_report(y_test_bnb, y_pred_bnb))

--- Bernoulli Naive Bayes Evaluation ---
Bernoulli Naive Bayes Accuracy: 1.0
Confusion Matrix:
[[6 0]
 [0 2]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      1.00      1.00         2

    accuracy                           1.00         8
   macro avg       1.00      1.00      1.00         8
weighted avg       1.00      1.00      1.00         8

### Conclusion

By implementing and evaluating Gaussian, Multinomial, and Bernoulli Naive Bayes classifiers, we have explored different facets of the Naive Bayes algorithm. The choice of which Naive Bayes model to use largely depends on the nature of your features (continuous, discrete counts, or binary).

In [1]:
#Naive bayes for Spam email detection

In [2]:
import pandas as pd

# Data representing 20 ham/spam messages
data = [
    {"Category": "ham", "Message": "Hey, are we still meeting for coffee at 4?"},
    {"Category": "spam", "Message": "CONGRATULATIONS! You've won a $500 Walmart gift card. Click here to claim."},
    {"Category": "ham", "Message": "I'll be a bit late for the meeting, please start without me."},
    {"Category": "spam", "Message": "Urgent: Your bank account has been compromised. Verify your identity now at bit.ly/secure-link."},
    {"Category": "ham", "Message": "Can you send me the notes from today's lecture?"},
    {"Category": "spam", "Message": "Get rich quick! Earn $5000 a week working from home. No experience needed."},
    {"Category": "ham", "Message": "Dinner is ready, come downstairs whenever you're done."},
    {"Category": "spam", "Message": "FREE entry into our annual prize draw. Text 'WIN' to 80011 to enter."},
    {"Category": "ham", "Message": "Did you see the latest episode of that show? It was wild."},
    {"Category": "spam", "Message": "Your Amazon package is waiting for delivery. Please confirm your address."},
    {"Category": "ham", "Message": "Happy Birthday! Hope you have a fantastic day."},
    {"Category": "spam", "Message": "Final Notice: Your car warranty is about to expire. Call now for a renewal."},
    {"Category": "ham", "Message": "The weather looks great for the hike tomorrow. Don't forget water!"},
    {"Category": "spam", "Message": "Dear Customer, you have an unclaimed tax refund of £450. Click to process."},
    {"Category": "ham", "Message": "I just pushed the latest updates to the GitHub repository."},
    {"Category": "spam", "Message": "Hot singles in your area want to meet you! Sign up for free today."},
    {"Category": "ham", "Message": "Let me know if you need any help with the project documentation."},
    {"Category": "spam", "Message": "Loan approved! Get up to $50,000 with 0% interest for the first year."},
    {"Category": "ham", "Message": "Are you coming to the football game tonight?"},
    {"Category": "spam", "Message": "Lowest prices on generic Viagra and Cialis. Order online now for 50% off."}
]

# Creating the DataFrame
df = pd.DataFrame(data)

# Display the first few rows to verify
print(df.head())

# Optional: Check the distribution of categories
print("\nValue Counts:")
print(df['Category'].value_counts())

  Category                                            Message
0      ham         Hey, are we still meeting for coffee at 4?
1     spam  CONGRATULATIONS! You've won a $500 Walmart gif...
2      ham  I'll be a bit late for the meeting, please sta...
3     spam  Urgent: Your bank account has been compromised...
4      ham    Can you send me the notes from today's lecture?

Value Counts:
Category
ham     10
spam    10
Name: count, dtype: int64

In [3]:
df.groupby('Category').describe()

         Message                                                            \
           count unique                                                top
Category
ham           10     10         Hey, are we still meeting for coffee at 4?
spam          10     10  CONGRATULATIONS! You've won a $500 Walmart gif...


         freq
Category
ham         1
spam        1

In [4]:
df['spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)
df.head()

  Category                                            Message  spam
0      ham         Hey, are we still meeting for coffee at 4?     0
1     spam  CONGRATULATIONS! You've won a $500 Walmart gif...     1
2      ham  I'll be a bit late for the meeting, please sta...     0
3     spam  Urgent: Your bank account has been compromised...     1
4      ham    Can you send me the notes from today's lecture?     0

In [5]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(df.Message,df.spam, test_size = 0.25)

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
x_train_count = v.fit_transform(x_train.values)
x_train_count.toarray()[:3]

array([[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
        1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
        0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0]])

In [10]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(x_train_count, y_train)

MultinomialNB()

In [11]:
emails = [
    'Hey mohan, can we get together to watch football game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you.f'
]
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [12]:
x_test_count = v.transform(x_test)
model.score(x_test_count, y_test)

0.8

In [ ]:
from sklearn.pipeline import Pipeline
clf = Piepline